name: Pulumi Pipeline de CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v2

      - name: Configura Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.12'

      - name: Configura token de acesso Pulumi
        run: echo "PULUMI_ACCESS_TOKEN=${{ secrets.PULUMI_ACCESS_TOKEN }}" >> $GITHUB_ENV

      - name: Instala dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Roda testes de infra
        run: |
          pulumi stack select dev
          pytest test_infra.py
